"""The instruments a trade may be journaled against.

The catalog is generated by ``backend/scripts/sync_instruments.py`` and read
from ``app/data/instruments.json`` at import — no network call on the request
path, and the file is a reviewable diff when a venue changes its specs.

It is also the single source of truth for how a trade's numbers are formatted:
every price must sit on the instrument's ``price_step`` and every position on
its ``size_step``.
"""

import json
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path


CATALOG_PATH = Path(__file__).resolve().parents[1] / "data" / "instruments.json"


@dataclass(frozen=True)
class Instrument:
    symbol: str
    name: str
    category: str
    venue: str
    price_step: Decimal
    size_step: Decimal


def _load() -> tuple[Instrument, ...]:
    rows = json.loads(CATALOG_PATH.read_text())

    return tuple(
        Instrument(
            symbol=row["symbol"],
            name=row["name"],
            category=row["category"],
            venue=row["venue"],
            price_step=Decimal(row["price_step"]),
            size_step=Decimal(row["size_step"]),
        )
        for row in rows
    )


INSTRUMENTS: tuple[Instrument, ...] = _load()

_BY_SYMBOL: dict[str, Instrument] = {
    instrument.symbol: instrument for instrument in INSTRUMENTS
}


def list_instruments() -> list[Instrument]:
    return list(INSTRUMENTS)


def get_instrument(symbol: str) -> Instrument | None:
    return _BY_SYMBOL.get(symbol)


def is_on_step(value: Decimal, step: Decimal) -> bool:
    """Whether a price or size lands on one of the instrument's increments."""
    return value % step == 0
